### ISSUE TITLE
Unable to get master_seed from https://blobvault.ripple.com/

### ISSUE THREAD

**Issue by koekiebox** [ripple/ripple-lib-java#70]
What is the username and password format to gain access to the master_seed via username and password?
Will the username and password (form my wallet) be my username and password from https://rippletrade.com?
Could there be another reason I am not able to access my wallet?

I am trying to run the CLI MakePayment.java example.
Also, what about 2-factor authentication?
Final, is the 'master_seed' the equivalent of the secret key?

Thank you.

**Comment by sublimator** [comment]
Oh, this is for the old version of the blob-vault. It needs updating. At
the least, probably removal. I'll see if I can get around to updating it
tho, as blobvault is a recent interest. Just read only access might not be
too difficult.

**Comment by sublimator** [comment]
> 'master_seed' the equivalent of the secret key?

Roughly speaking, yes. It's what you are told to backup by RippleTrade,
when they say "back up your secret key".

It's a 128 bit value, that is hashed in a loop, until the hash, as a
number, is a valid for the elliptic curve. Thus `seed`. The `master` part
comes from the fact that the public key, a function of the secret curve
number, is hashed and used as the address (account identifier). With ripple
you can set another keypair with the SetRegularKey transaction. These are
called `regular` keys, as opposed to master. So you can sign transactions
with a secondary key, and keep the master key backed up safely offline.

**Comment by koekiebox** [comment]
Thanks for the explanation. :-). Works like a charm now.
