### ISSUE TITLE
 Amendments enum missing

### ISSUE THREAD

**Issue by veckman** [ripple/ripple-lib-java#73]
When connecting to a rippled server I got that:

java.lang.RuntimeException: Couldn't put
`{"LedgerEntryType":"Amendments","PreviousFields":{"Majorities":[{"Majority":{"Amendment":"42426C4D4F1009EE67080A9B7965B44656D7714D104A72F9B4369F97ABF044EE","CloseTime":515781202}}]},"FinalFields":{"Amendments":["42426C4D4F1009EE67080A9B7965B44656D7714D104A72F9B4369F97ABF044EE"],"Flags":0},"LedgerIndex":"7DB0788C020F02780A673DC74757F23823FA3014C1866E72CC4CD8B226CD6EF4"}`
into field `ModifiedNode`
java.lang.RuntimeException: Couldn't put `Amendments` into field
`LedgerEntryType`
java.lang.IllegalArgumentException: No enum constant
com.ripple.core.serialized.enums.LedgerEntryType.Amendments

Is it fixed?

Thanks

**Comment by sublimator** [comment]
It needs updating to add the new binary serialisation fields. I will do it
in the next few days :)

**Comment by sublimator** [comment]
Hey, I just pushed a commit with updated definitions

**Comment by sublimator** [comment]
Fixed with 4358958586ed722625ca89d29b9b6bfa517803f0

**Comment by veckman** [comment]
Thanks
